<?xml version="1.0"?>
<case xmlns="http://commcarehq.org/case/transaction/v2" case_id="$caseId$" date_modified="2012-04-03" user_id="$userId$">
    <create>
        <case_type>cc_bihar_pregnancy</case_type>
        <case_name>NEERAJ</case_name>
        <owner_id>$ownerId$</owner_id>
    </create>
    <update>
        <add/>
        <age>25</age>
        <date_last_visit>2012-04-03</date_last_visit>
        <date_next_bp>2012-04-03</date_next_bp>
        <date_next_reg>2012-04-03</date_next_reg>
        <edd></edd>
        <family_number>3</family_number>
        <family_planning_type>ppiud_at_delivery</family_planning_type>
        <hh_number>224</hh_number>
        <husband_name>DA</husband_name>
        <last_visit_type>reg</last_visit_type>
        <lmp>2012-01-20</lmp>
        <mobile_number>2254451212</mobile_number>
        <mother_alive>yes</mother_alive>
        <mother_dob>1986-04-25</mother_dob>
        <mother_name>NEERAJ</mother_name>
        <num_boys>1</num_boys>
        <last_preg_tt>no</last_preg_tt>
    </update>
</case>