<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="Registration" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/registration">
<n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
<n0:deviceID>T5Y0ATKMW970QJ63YHF1V1QW1</n0:deviceID>
<n0:timeStart>2012-04-19T11:53:35.806Z</n0:timeStart>
<n0:timeEnd>2012-04-19T11:58:35.429Z</n0:timeEnd>
<n0:username>motech</n0:username>
<n0:userID>$userId$</n0:userID>
<n0:instanceID>$instanceId$</n0:instanceID>
<cc:appVersion>v1.4.0dev (b0a68b-908411-unvers-2.1.0-Nokia/S40-generic) #12 b:2012-Apr-02 r:2012-Apr-03</cc:appVersion>
</n0:meta>
<n1:case case_id="$caseId$" date_modified="2012-04-19" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
<n1:update>
<n1:mobile_number>2158461</n1:mobile_number>
<n1:mother_dob>1982-10-20</n1:mother_dob>
<n1:num_boys>3</n1:num_boys>
<n1:add />
<n1:last_visit_type>reg</n1:last_visit_type>
<n1:date_last_visit>2012-04-19</n1:date_last_visit>
<n1:family_planning_type />
<n1:edd>$edd$</n1:edd>
<n1:age>29</n1:age>
<n1:lmp>2011-07-24</n1:lmp>
<n1:last_preg_tt>no</n1:last_preg_tt>
<n1:date_next_bp>2012-04-19</n1:date_next_bp>
</n1:update>
</n1:case>
<jsy_beneficiary>yes</jsy_beneficiary>
<display_name>OK</display_name>
<children>yes</children>
<num_girls>0</num_girls>
<num_boys>3</num_boys>
<education>inter</education>
<mobile_number_whose>mobile_asha</mobile_number_whose>
<resident>resident</resident>
<vegetarian>yes</vegetarian>
<is_pregnant>yes</is_pregnant>
<urine_test>yes</urine_test>
<lmp_known>no</lmp_known>
<edd_known>no</edd_known>
<gest_age>9</gest_age>
<show_edd>OK</show_edd>
<preg_desired>no</preg_desired>
<continue_preg>no</continue_preg>
<last_preg>2</last_preg>
<last_preg_full_term>no</last_preg_full_term>
<last_preg_c_section>no</last_preg_c_section>
<num_children>0</num_children>
<used_fp>no</used_fp>
<good_to_register>yes</good_to_register>
<success>OK</success>
<dob_est />
<age_calc>29</age_calc>
<lmp_calc>2011-07-24</lmp_calc>
<nextvisit_bp>OK</nextvisit_bp>
<nextvisittype>bp</nextvisittype>
<temp />
</data>