<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="New Beneficiary" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/new">
<n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
<n0:deviceID>T5Y0ATKMW970QJ63YHF1V1QW1</n0:deviceID>
<n0:timeStart>2012-04-19T11:17:50.522Z</n0:timeStart>
<n0:timeEnd>2012-04-19T11:18:47.148Z</n0:timeEnd>
<n0:username>care</n0:username>
<n0:userID>$userId$</n0:userID>
<n0:instanceID>$instanceId$</n0:instanceID>
<cc:appVersion>v1.4.0dev (b0a68b-908411-unvers-2.1.0-Nokia/S40-generic) #12 b:2012-Apr-02 r:2012-Apr-03</cc:appVersion>
</n0:meta>
<n1:case case_id="$caseId$" date_modified="2012-04-19" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
<n1:create>
<n1:case_type>cc_bihar_pregnancy</n1:case_type>
<n1:owner_id>$ownerId$</n1:owner_id>
<n1:case_name>$name$</n1:case_name>
</n1:create>
<n1:update>
<n1:last_visit_type>new</n1:last_visit_type>
<n1:date_last_visit>2012-04-19</n1:date_last_visit>
<n1:date_next_reg>2012-04-19</n1:date_next_reg>
<n1:mother_alive>yes</n1:mother_alive>
<n1:mother_name>$name$</n1:mother_name>
<n1:husband_name>MOHAN</n1:husband_name>
<n1:hh_number>5</n1:hh_number>
<n1:family_number>2</n1:family_number>
<n1:mother_dob>1982-10-20</n1:mother_dob>
</n1:update>
</n1:case>
<full_name>$name$</full_name>
<husband_name>MOHAN</husband_name>
<hh_number>5</hh_number>
<family_number>2</family_number>
<dob_known>yes</dob_known>
<dob>1982-10-20</dob>
<show_age>OK</show_age>
<caste>other</caste>
<success>OK</success>
<age_calc>29</age_calc>
</data>