<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="Registration" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/registration">
<n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
<n0:deviceID>T5Y0ATKMW970QJ63YHF1V1QW1</n0:deviceID>
<n0:timeStart>2012-04-17T15:38:23.673Z</n0:timeStart>
<n0:timeEnd>2012-04-17T15:41:40.790Z</n0:timeEnd>
<n0:username>care</n0:username>
<n0:userID>d823ea3d392a06f8b991e9e4933348bd</n0:userID>
<n0:instanceID>$instanceId$</n0:instanceID>
<cc:appVersion>v1.4.0dev (b0a68b-908411-unvers-2.1.0-Nokia/S40-generic) #12 b:2012-Apr-02 r:2012-Apr-03</cc:appVersion>
</n0:meta>
<n1:case case_id="$caseId$" date_modified="2012-04-17" user_id="d823ea3d392a06f8b991e9e4933348bd" xmlns:n1="http://commcarehq.org/case/transaction/v2">
<n1:update>
<n1:mobile_number>55862</n1:mobile_number>
<n1:mother_dob>1981-04-17</n1:mother_dob>
<n1:num_boys>1</n1:num_boys>
<n1:add />
<n1:last_visit_type>reg</n1:last_visit_type>
<n1:date_last_visit>2012-04-17</n1:date_last_visit>
<n1:family_planning_type />
<n1:edd>$edd$</n1:edd>
<n1:age>31</n1:age>
<n1:lmp>2012-02-17</n1:lmp>
<n1:last_preg_tt>no</n1:last_preg_tt>
<n1:date_next_bp>2012-04-17</n1:date_next_bp>
</n1:update>
</n1:case>
<jsy_beneficiary>yes</jsy_beneficiary>
<display_name>OK</display_name>
<children>yes</children>
<num_girls>1</num_girls>
<num_boys>1</num_boys>
<education>metric</education>
<mobile_number_whose>mobile_mine</mobile_number_whose>
<resident>resident</resident>
<vegetarian>yes</vegetarian>
<is_pregnant>yes</is_pregnant>
<urine_test>yes</urine_test>
<lmp_known>no</lmp_known>
<edd_known>no</edd_known>
<gest_age>2</gest_age>
<show_edd>OK</show_edd>
<preg_desired>yes</preg_desired>
<last_preg>1</last_preg>
<last_preg_full_term>no</last_preg_full_term>
<last_preg_c_section>yes</last_preg_c_section>
<num_children>0</num_children>
<used_fp>no</used_fp>
<good_to_register>yes</good_to_register>
<success>OK</success>
<dob_est />
<age_calc>31</age_calc>
<lmp_calc>2012-02-17</lmp_calc>
<nextvisit_bp>OK</nextvisit_bp>
<nextvisittype>bp</nextvisittype>
<temp />
</data>